CREATE TABLE LAB_EQUIPMENT (
    EQUIPMENT_ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    NAME VARCHAR(100) NOT NULL,
    DEPARTMENT VARCHAR(100) NOT NULL,
    PURCHASE_DATE DATE NOT NULL,
    CONDITION VARCHAR(50) NOT NULL,
    IN_USE BOOLEAN NOT NULL,
    PRICE DECIMAL(10,2) NOT NULL CHECK (PRICE >= 0)
);

INSERT INTO LAB_EQUIPMENT (NAME, DEPARTMENT, PURCHASE_DATE, CONDITION, IN_USE, PRICE)
VALUES ('Desktop PC', 'Computer Science', DATE('2023-02-10'), 'New', TRUE, 14500.00);

INSERT INTO LAB_EQUIPMENT (NAME, DEPARTMENT, PURCHASE_DATE, CONDITION, IN_USE, PRICE)
VALUES ('Webcam', 'Computer Science', DATE('2023-03-12'), 'New', TRUE, 1250.00);

INSERT INTO LAB_EQUIPMENT (NAME, DEPARTMENT, PURCHASE_DATE, CONDITION, IN_USE, PRICE)
VALUES ('Mechanical Keyboard', 'Computer Science', DATE('2022-05-18'), 'Used', TRUE, 950.00);

INSERT INTO LAB_EQUIPMENT (NAME, DEPARTMENT, PURCHASE_DATE, CONDITION, IN_USE, PRICE)
VALUES ('VR Headset', 'Computer Science', DATE('2024-01-22'), 'New', FALSE, 12750.00);

INSERT INTO LAB_EQUIPMENT (NAME, DEPARTMENT, PURCHASE_DATE, CONDITION, IN_USE, PRICE)
VALUES ('Laser Printer', 'Information Technology', DATE('2022-11-05'), 'Used', FALSE, 7600.00);

INSERT INTO LAB_EQUIPMENT (NAME, DEPARTMENT, PURCHASE_DATE, CONDITION, IN_USE, PRICE)
VALUES ('Network Switch', 'Information Technology', DATE('2023-01-15'), 'New', TRUE, 9350.00);

INSERT INTO LAB_EQUIPMENT (NAME, DEPARTMENT, PURCHASE_DATE, CONDITION, IN_USE, PRICE)
VALUES ('External Hard Drive', 'Information Technology', DATE('2022-09-25'), 'Used', FALSE, 1850.00);

INSERT INTO LAB_EQUIPMENT (NAME, DEPARTMENT, PURCHASE_DATE, CONDITION, IN_USE, PRICE)
VALUES ('Wi-Fi Router', 'Information Technology', DATE('2021-07-14'), 'Damaged', FALSE, 2100.00);

INSERT INTO LAB_EQUIPMENT (NAME, DEPARTMENT, PURCHASE_DATE, CONDITION, IN_USE, PRICE)
VALUES ('Server Rack', 'Information Technology', DATE('2020-10-09'), 'Used', TRUE, 18900.00);

INSERT INTO LAB_EQUIPMENT (NAME, DEPARTMENT, PURCHASE_DATE, CONDITION, IN_USE, PRICE)
VALUES ('Projector', 'Informatics', DATE('2021-08-20'), 'Used', TRUE, 11200.00);

INSERT INTO LAB_EQUIPMENT (NAME, DEPARTMENT, PURCHASE_DATE, CONDITION, IN_USE, PRICE)
VALUES ('Document Scanner', 'Informatics', DATE('2024-04-18'), 'New', FALSE, 6800.00);

INSERT INTO LAB_EQUIPMENT (NAME, DEPARTMENT, PURCHASE_DATE, CONDITION, IN_USE, PRICE)
VALUES ('Tablet', 'Informatics', DATE('2023-06-11'), 'New', TRUE, 8900.00);

INSERT INTO LAB_EQUIPMENT (NAME, DEPARTMENT, PURCHASE_DATE, CONDITION, IN_USE, PRICE)
VALUES ('Digital Whiteboard', 'Informatics', DATE('2022-02-16'), 'Used', TRUE, 24500.00);

INSERT INTO LAB_EQUIPMENT (NAME, DEPARTMENT, PURCHASE_DATE, CONDITION, IN_USE, PRICE)
VALUES ('UPS Battery Backup', 'Computer Systems Engineering', DATE('2020-06-30'), 'Damaged', FALSE, 5200.00);

INSERT INTO LAB_EQUIPMENT (NAME, DEPARTMENT, PURCHASE_DATE, CONDITION, IN_USE, PRICE)
VALUES ('Oscilloscope', 'Computer Systems Engineering', DATE('2023-08-21'), 'New', TRUE, 32800.00);

INSERT INTO LAB_EQUIPMENT (NAME, DEPARTMENT, PURCHASE_DATE, CONDITION, IN_USE, PRICE)
VALUES ('Soldering Station', 'Computer Systems Engineering', DATE('2021-04-07'), 'Used', TRUE, 3400.00);

INSERT INTO LAB_EQUIPMENT (NAME, DEPARTMENT, PURCHASE_DATE, CONDITION, IN_USE, PRICE)
VALUES ('Microcontroller Kit', 'Computer Systems Engineering', DATE('2024-02-13'), 'New', TRUE, 2750.00);

INSERT INTO LAB_EQUIPMENT (NAME, DEPARTMENT, PURCHASE_DATE, CONDITION, IN_USE, PRICE)
VALUES ('Signal Generator', 'Computer Systems Engineering', DATE('2019-11-28'), 'Damaged', FALSE, 15800.00);

INSERT INTO LAB_EQUIPMENT (NAME, DEPARTMENT, PURCHASE_DATE, CONDITION, IN_USE, PRICE)
VALUES ('Digital Camera', 'Multimedia', DATE('2023-09-04'), 'New', TRUE, 21900.00);

INSERT INTO LAB_EQUIPMENT (NAME, DEPARTMENT, PURCHASE_DATE, CONDITION, IN_USE, PRICE)
VALUES ('Studio Microphone', 'Multimedia', DATE('2022-03-19'), 'Used', FALSE, 4700.00);

SELECT * FROM APP.LAB_EQUIPMENT ORDER BY EQUIPMENT_ID;